create database libs;
use libs;

Create Table LMS_BOOK_ISSUE(
BOOK_ISSUE_NO int not null auto_increment PRIMARY KEY,
MEMBER_ID varchar(10),
BOOK_CODE VARCHAR(10),
DATE_ISSUE DATE,
DATE_RETURN DATE,
DATE_RETURNED DATE,
BOOK_ISSUE_STATUS VARCHAR(20),
FINE_RANGE VARCHAR(3)
);

ALTER TABLE lms_book_details
MODIFY BOOK_CODE int not null auto_increment;

alter table LMS_BOOK_ISSUE
add memFk int;

alter table LMS_BOOK_ISSUE
add foreign key (memFk) references lms_members(MEMBER_ID);

alter table LMS_BOOK_ISSUE
modify BidFk varchar(10);

alter table LMS_BOOK_ISSUE
add foreign key (BidFk) references lms_book_details(BOOK_CODE);

alter table LMS_BOOK_ISSUE
add FrFk int(11);

alter table LMS_BOOK_ISSUE
add foreign key (FrFk) references lms_fine_details(FINE_RANGE);

alter table lms_book_details
add SidFk int(11);

alter table lms_book_details
add foreign key (SidFk) references lms_supplier_details(SUPPLIER_ID);





SELECT * FROM lms_book_issue;



INSERT INTO lms_book_issue SET  MEMBER_ID='MEM1',BOOK_CODE='1001',DATE_ISSUE=20190702,DATE_RETURN=20190710,DATE_RETURNED=20190709,
BOOK_ISSUE_STATUS='Y',FINE_RANGE=3;
INSERT INTO lms_book_issue SET  MEMBER_ID='MEM2',BOOK_CODE='1002',DATE_ISSUE=20190921,DATE_RETURN=20190921,DATE_RETURNED=20190921,
BOOK_ISSUE_STATUS='N',FINE_RANGE=3;
INSERT INTO lms_book_issue SET  MEMBER_ID='MEM3',BOOK_CODE='1003',DATE_ISSUE=20190820,DATE_RETURN=20190921,DATE_RETURNED=20190921,
BOOK_ISSUE_STATUS='Y',FINE_RANGE=3;
INSERT INTO lms_book_issue SET  MEMBER_ID='MEM5',BOOK_CODE='012',DATE_ISSUE=20190922,DATE_RETURN=20190921,DATE_RETURNED=20190921,
BOOK_ISSUE_STATUS='Y',FINE_RANGE=3;

SELECT * FROM lms_book_issue;

create table LMS_BOOK_DETAILS
(
	BOOK_CODE VARCHAR(10),
    BOOK_TITLE VARCHAR(50),
    CATEGORY VARCHAR(15),
    AUTHOR VARCHAR(30),
    PUBLICATION VARCHAR(3),
    PUBLISH_DATE DATE,
    BOOK_EDITION INT,
    PRICE INT,
    RACK_NUM VARCHAR(3),
    DATE_ARRIVAL DATE,
    SUPPLIER_ID int(3),
    PRIMARY KEY (BOOK_CODE)
);
/*LMS_SUPPLIE_DETAILS*/
CREATE TABLE LMS_SUPPLIER_DETAILS
(
	SUPPLIER_ID int(3) auto_increment,
    SUPPLIER_NAME VARCHAR(30),
    ADDRESS VARCHAR(50),
    CONTACT VARCHAR(20),
    EMAIL VARCHAR(30),
    PRIMARY KEY(SUPPLIER_ID)
);
alter table LMS_BOOK_DETAILS
add foreign key (SUPPLIER_ID) references LMS_SUPPLIER_DETAILS(SUPPLIER_ID);
drop table LMS_BOOK_DETAILS;
select *from LMS_BOOK_DETAILS;
select *from LMS_SUPPLIER_DETAILS;

create table LMS_members
(
MEMBER_ID int(20) not null auto_increment,
MEMBER_NAME VARCHAR(30),
CITY VARCHAR(20),
DATE_REGISTER DATE,
DATE_EXPRE DATE,
MEMBERSHIP_STATUS VARCHAR(15),
PRIMARY KEY (MEMBER_ID)
);

create table LMS_FINE_DETAILS
(

FINE_RANGE int auto_increment,
FINE_AMOUNT INT,
PRIMARY KEY (FINE_RANGE)
);
insert into  LMS_BOOK_DETAILS set BOOK_CODE=' 002',BOOK_TITLE ='hunger games',CATEGORY ='fiction',AUTHOR='john green',
PUBLICATION ='AAA',PUBLISH_DATE='1998-08-26',BOOK_EDITION ='4',PRICE='450',RACK_NUM='01',DATE_ARRIVAL ='2018-04-26';
insert into  LMS_BOOK_DETAILS set BOOK_CODE=' 003',BOOK_TITLE ='catching fire',CATEGORY ='fiction',AUTHOR='john green',
PUBLICATION ='AAA',PUBLISH_DATE='1998-10-30',BOOK_EDITION ='4',PRICE='150',RACK_NUM='01',DATE_ARRIVAL ='2018-04-26';
insert into  LMS_BOOK_DETAILS set BOOK_CODE=' 004',BOOK_TITLE ='mockingjay',CATEGORY ='fiction',AUTHOR='john green',
PUBLICATION ='AAA',PUBLISH_DATE='2000-10-15',BOOK_EDITION ='4',PRICE='200',RACK_NUM='01',DATE_ARRIVAL ='2018-04-26';
insert into  LMS_BOOK_DETAILS set BOOK_CODE=' 005',BOOK_TITLE ='alchemist',CATEGORY ='fiction',AUTHOR='paulo coehlo',
PUBLICATION ='AAA',PUBLISH_DATE='1998-08-26',BOOK_EDITION ='4',PRICE='250',RACK_NUM='01',DATE_ARRIVAL ='2018-04-26';
insert into  LMS_BOOK_DETAILS set BOOK_CODE=' 006',BOOK_TITLE ='wings of fire',CATEGORY ='autobiograpghy',AUTHOR='APJ ABDUL KALAM',
PUBLICATION ='AAA',PUBLISH_DATE='2000-08-26',BOOK_EDITION ='5',PRICE='500',RACK_NUM='01',DATE_ARRIVAL ='2018-04-26';

insert  into LMS_SUPPLIER_DETAILS SET SUPPLIER_NAME ='RAMDAS',ADDRESS ='ABC STREET',CONTACT='9446320769',EMAIL ='anjayaram@gmail.com';
insert  into LMS_SUPPLIER_DETAILS SET SUPPLIER_NAME ='RAM',ADDRESS ='DEF STREET',CONTACT='9446320789',EMAIL ='ram@gmail.com';
insert  into LMS_SUPPLIER_DETAILS SET SUPPLIER_NAME ='RIYA',ADDRESS ='GHI STREET',CONTACT='9444560789',EMAIL ='riya@gmail.com';
insert  into LMS_SUPPLIER_DETAILS SET SUPPLIER_NAME ='liya',ADDRESS ='nml STREET',CONTACT='94445607819',EMAIL ='liya@gmail.com';


insert into LMS_FINE_DETAILS set FINE_AMOUNT ='50';
insert into LMS_FINE_DETAILS set FINE_AMOUNT ='5';
insert into LMS_FINE_DETAILS set FINE_AMOUNT ='15';
insert into LMS_FINE_DETAILS set FINE_AMOUNT ='50';


insert into LMS_members set MEMBER_NAME ='devika',CITY = 'thrissur',DATE_REGISTER ='2000-08-26',DATE_EXPRE= '2000-08-31',MEMBERSHIP_STATUS ='permenant';
insert into LMS_members set MEMBER_NAME ='keerthana',CITY = 'mumbai',DATE_REGISTER ='2000-08-01',DATE_EXPRE= '2000-08-07',MEMBERSHIP_STATUS ='temp';
insert into LMS_members set MEMBER_NAME ='sahil',CITY = 'delhi',DATE_REGISTER ='2000-08-15',DATE_EXPRE= '2000-08-21',MEMBERSHIP_STATUS ='permanent';
insert into LMS_members set MEMBER_NAME ='sanchit',CITY = 'delhi',DATE_REGISTER ='2000-08-17',DATE_EXPRE= '2000-08-23',MEMBERSHIP_STATUS ='temp';

select * from LMS_BOOK_ISSUE;
select * from LMS_BOOK_DETAILS;
select * from LMS_SUPPLIER_DETAILS;
select * from LMS_members;
select * from LMS_FINE_DETAILS;

select MEMBER_ID,MEMBER_NAME,CITY,MEMBERSHIP_STATUS
from LMS_members
where MEMBERSHIP_STATUS='permanent';

select MEMBER_ID
from lms_book_issue 
where BOOK_ISSUE_STATUS='Y';

SELECT LMS_members.MEMBER_ID,LMS_BOOK_ISSUE.BOOK_ISSUE_STATUS,LMS_members.MEMBER_NAME
FROM LMS_members
INNER JOIN LMS_BOOK_ISSUE ON LMS_members.BOOK_ISSUE_STATUS=LMS_BOOK_ISSUE.BOOK_ISSUE_STATUS;

SELECT MEMBER_NAME,BOOK_ISSUE_STATUS,LM.MEMBER_ID
  FROM LMS_members AS LM JOIN LMS_BOOK_ISSUE;
  
  SELECT MEMBER_ID,MEMBER_NAME
  FROM LMS_members
  WHERE BOOK_CODE='BL000002';
  
  
  SELECT BOOK_CODE,BOOK_TITLE,AUTHOR
  FROM LMS_BOOK_DETAILS
  WHERE AUTHOR LIKE 'P%';
  
  insert into  LMS_BOOK_DETAILS set BOOK_CODE=' 012',BOOK_TITLE ='JAVA',CATEGORY ='PROGRAM',AUTHOR='john green',
PUBLICATION ='AAA',PUBLISH_DATE='1998-08-26',BOOK_EDITION ='6',PRICE='450',RACK_NUM='01',DATE_ARRIVAL ='2018-04-26';
  
  SELECT COUNT(BOOK_TITLE)AS NO_OF_BOOKS
FROM LMS_BOOK_DETAILS
WHERE BOOK_TITLE ='JAVA';

 insert into  LMS_BOOK_DETAILS set BOOK_CODE=' 010',BOOK_TITLE ='JAVA',CATEGORY ='PROGRAM',AUTHOR='john green',
PUBLICATION ='AAA',PUBLISH_DATE='2012-04-1',BOOK_EDITION ='4',PRICE='450',RACK_NUM='01',DATE_ARRIVAL ='2018-04-26';
  


SELECT BOOK_CODE,BOOK_TITLE
FROM LMS_BOOK_DETAILS
WHERE PUBLISH_DATE='2012-04-1';

SELECT MEMBER_ID,
MEMBER_NAME,DATE_EXPRE  
FROM LMS_members
WHERE DATE_EXPRE<'2013-04-01';


SELECT MEMBER_NAME,MEMBER_ID,DATE_REGISTER,DATE_EXPRE
FROM LMS_members
WHERE DATE_REGISTER<'2012-03-01' AND MEMBERSHIP_STATUS='temp';


SELECT MEMBER_ID,MEMBER_NAME as NAME
FROM LMS_members
WHERE CITY ='delhi'or 'chennai';


select BOOK_TITLE ||"is written by"|| AUTHOR as BOOK_WRITTRN_BY
from LMS_BOOK_DETAILS;


SELECT AVG(PRICE) AS AveragePrice FROM LMS_BOOK_DETAILS
WHERE BOOK_TITLE ='JAVA';

SELECT SUPPLIER_ID ,SUPPLIER_NAME, EMAIL FROM LMS_SUPPLIER_DETAILS WHERE EMAIL like '%gmail.com';


select SUPPLIER_ID ,SUPPLIER_NAME ,coalesce(ADDRESS,EMAIL,CONTACT) AS CONTACT_DETAILS
FROM LMS_SUPPLIER_DETAILS;

SELECT SUPPLIER_ID ,SUPPLIER_NAME,CONTACT,
NVL2 (CONTACT, 'YES','NO')AS PHONE_NO_AVAILABLE
  FROM LMS_SUPPLIER_DETAILS ;
  select SUPPLIER_ID,SUPPLIER_NAME,case when CONTACT is NULL then 'NO' when CONTACT is not null then 'YES' end as PHONE_NUM_AVAILABLE from LMS_SUPPLIER_DETAILS ;
  
  SELECT MEMBER_ID,MEMBER_NAME,BOOK_CODE,BOOK_TITLE
  FROM LMS_members NATURAL JOIN LMS_BOOK_DETAILS;
  
SELECT COUNT(BOOK_CODE)AS NO_OF_BOOKS
FROM LMS_BOOK_ISSUE
WHERE BOOK_ISSUE_STATUS='N';


SELECT MEMBER_ID,MEMBER_NAME,FINE_RANGE,FINE_AMOUNT
  FROM LMS_members NATURAL JOIN LMS_FINE_DETAILS WHERE FINE_AMOUNT<100;
  
SELECT BOOK_CODE,BOOK_TITLE,BOOK_ISSUE_STATUS AS AVAILABILITY_OF_BOOKS 
  FROM LMS_BOOK_DETAILS NATURAL JOIN lms_book_issue WHERE (BOOK_TITLE='JAVA' AND BOOK_EDITION='6');
  
  insert into  LMS_BOOK_DETAILS set BOOK_CODE=' 111',BOOK_TITLE ='hunger games',CATEGORY ='fiction',AUTHOR='john green',
PUBLICATION ='AAA',PUBLISH_DATE='1998-08-26',BOOK_EDITION ='4',PRICE='450',RACK_NUM='A1',DATE_ARRIVAL ='2018-04-26';

insert into  LMS_BOOK_DETAILS set BOOK_CODE=' 112',BOOK_TITLE ='wings of fire',CATEGORY ='autobiograpghy',AUTHOR='APJ ABDUL KALAM',
PUBLICATION ='AAA',PUBLISH_DATE='2000-08-26',BOOK_EDITION ='5',PRICE='500',RACK_NUM='A1',DATE_ARRIVAL ='2018-04-26';

SELECT BOOK_CODE,BOOK_TITLE,RACK_NUM
FROM LMS_BOOK_DETAILS
WHERE RACK_NUM='A1'
GROUP BY BOOK_TITLE;

