create database libmansys;
use libmansys;
/*LMS_BOOK_DETAILS*/
create table LMS_BOOK_DETAILS
(
	BOOK_CODE VARCHAR(10),
    BOOK_TITLE VARCHAR(50),
    CATEGORY VARCHAR(15),
    AUTHOR VARCHAR(30),
    PUBLICATION VARCHAR(3),
    PUBLISH_DATE DATE,
    BOOK_EDITION INT,
    PRICE INT,
    RACK_NUM VARCHAR(3),
    DATE_ARRIVAL DATE,
    SUPPLIER_ID int(3),
    PRIMARY KEY (BOOK_CODE)
);
/*LMS_SUPPLIE_DETAILS*/
CREATE TABLE LMS_SUPPLIER_DETAILS
(
	SUPPLIER_ID int(3) auto_increment,
    SUPPLIER_NAME VARCHAR(30),
    ADDRESS VARCHAR(50),
    CONTACT VARCHAR(20),
    EMAIL VARCHAR(30),
    PRIMARY KEY(SUPPLIER_ID)
);
alter table LMS_BOOK_DETAILS
add foreign key (SUPPLIER_ID) references LMS_SUPPLIER_DETAILS(SUPPLIER_ID);
drop table LMS_BOOK_DETAILS;
select *from LMS_BOOK_DETAILS;
select *from LMS_SUPPLIER_DETAILS;
